[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = 'javascript'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'javascript', 'php']
hook_add = '''
  let g:closetag_filetypes = 'html,xhtml,phtml,javascript'
  let g:closetag_shortcut = '>>'
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# surround completion
[[plugins]]
repo = "cohama/lexima.vim"
hook_post_source = '''
  call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '(', 'input': '('})
  call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '[', 'input': '['})
  call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '{', 'input': '{'})
'''
on_i = 1

# word completion management
[[plugins]]
repo = "Shougo/deoplete.nvim"
if = "has('python3')"
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

# deoplete dependency
[[plugins]]
repo = 'roxma/nvim-yarp'
on_i = 1

# deoplete dependency
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_i = 1

# word completion
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

