# plugin管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'

# ファイルツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e>t :NERDTreeToggle<CR>
  nnoremap <silent><C-e>f :NERDTreeFind<CR>
'''

# ファイルツリーにgit status表示
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# git関連
[[plugins]]
repo = "airblade/vim-gitgutter"

# git関連
[[plugins]]
repo = "tpope/vim-fugitive"

# ファイル名検索
[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
hook_add = '''
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

# 囲み補完
[[plugins]]
repo = "cohama/lexima.vim"

# 補完用プラグイン
[[plugins]]
repo = "Shougo/deoplete.nvim"
if = "has('python3')"
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
  set completeopt+=noinsert
'''

# deopleteに必要
[[plugins]]
repo = 'roxma/nvim-yarp'

# deopleteに必要
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# deopleteの補完候補プラグイン
[[plugins]]
repo = 'Shougo/neco-syntax'

# fast grep
[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
  let g:ackprg = 'ag --nogroup --nocolor --column'
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
