[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = 'javascript'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'
hook_add = 'autocmd BufRead,BufNewFile *.slim setfiletype slim'
