# plugin管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'

# ファイルツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'

# ファイルツリーにgit status表示
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# git関連
[[plugins]]
repo = "airblade/vim-gitgutter"

# git関連
[[plugins]]
repo = "tpope/vim-fugitive"

# ファイル名検索
[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
hook_add = '''
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

# 囲み補完
[[plugins]]
repo = "cohama/lexima.vim"
