# plugin management
[[plugins]]
repo = 'Shougo/dein.vim'

# async load
[[plugins]]
repo = 'Shougo/vimproc.vim'

# file tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e>t :NERDTreeToggle<CR>
  nnoremap <silent><C-e>f :NERDTreeFind<CR>
  " launch with nerdtree when no file specified
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  " terminate vim when only nerdtree exists
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
  let g:NERDTreeIgnore = ['^\.DS_Store$', '^\.git$']
  let g:NERDTreeShowHidden = 1
'''

# show git status on file tree
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# git related
[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
  set signcolumn=yes
  set updatetime=100
'''

# git related
[[plugins]]
repo = "tpope/vim-fugitive"

# search by file name
[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
hook_add = '''
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

# fast grep
[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
  let g:ackprg = 'ag --nogroup --nocolor --column'
'''

# replace for quickfix
[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'tpope/vim-surround'

# customize status bar 
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode

  let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head',
    \   'filename': 'LightlineFilename',
    \ },
    \ }

    function! LightlineFilename()
      let root = fnamemodify(get(b:, 'git_dir'), ':h')
      let path = expand('%:p')
      if path[:len(root)-1] ==# root
        return path[len(root)+1:]
      endif
      return expand('%')
    endfunction
'''

# visualize indent
[[plugins]]
repo = 'Yggdroot/indentLine'
