# plugin管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'

# ファイルツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'


# git関連
[[plugins]]
repo = "airblade/vim-gitgutter"

# git関連
[[plugins]]
repo = "tpope/vim-fugitive"
